import { Resend } from 'resend';

const resendApiKey = process.env.RESEND_API_KEY;
const resend = resendApiKey ? new Resend(resendApiKey) : null;
const FROM_ADDRESS = process.env.EMAIL_FROM || 'API Sorter System <system@apisorter.com>';
const ADMIN_EMAIL = process.env.ADMIN_EMAIL || 'admin@apisorter.com'; // Fallback, should be in env

export interface CrawlerStats {
    total: number;
    success: number;
    failed: number;
    durationMs: number;
    errors: Array<{
        name: string;
        url: string;
        error: string;
    }>;
}

export async function sendCrawlerReport(stats: CrawlerStats) {
    if (!resend) {
        console.warn('[Alerts] RESEND_API_KEY not configured. Skipping admin report.');
        return;
    }

    const subject = `[Crawler Report] ${stats.success}/${stats.total} Success - ${new Date().toLocaleDateString()}`;

    const errorRows = stats.errors.map(e => `
    <tr>
      <td style="padding: 8px; border-bottom: 1px solid #eee;">${e.name}</td>
      <td style="padding: 8px; border-bottom: 1px solid #eee;"><a href="${e.url}">${e.url}</a></td>
      <td style="padding: 8px; border-bottom: 1px solid #eee; color: red;">${e.error}</td>
    </tr>
  `).join('');

    const errorTable = stats.errors.length > 0 ? `
    <h3 style="margin-top: 20px;">Failed URLs</h3>
    <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
      <thead>
        <tr style="background: #f5f5f5; text-align: left;">
          <th style="padding: 8px;">Name</th>
          <th style="padding: 8px;">URL</th>
          <th style="padding: 8px;">Error</th>
        </tr>
      </thead>
      <tbody>
        ${errorRows}
      </tbody>
    </table>
  ` : '<p style="color: green;">No errors reported.</p>';

    const html = `
    <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;">
      <h2>Crawler Execution Report</h2>
      <div style="background: #f8fafc; padding: 16px; border-radius: 8px; border: 1px solid #e2e8f0;">
        <p><strong>Total Processed:</strong> ${stats.total}</p>
        <p><strong>Success:</strong> ${stats.success}</p>
        <p><strong>Failed:</strong> ${stats.failed}</p>
        <p><strong>Duration:</strong> ${(stats.durationMs / 1000).toFixed(1)}s</p>
      </div>

      ${errorTable}
      
      <p style="margin-top: 30px; font-size: 12px; color: #666;">
        Generated by API Sorter Automation System at ${new Date().toISOString()}
      </p>
    </div>
  `;

    try {
        await resend.emails.send({
            from: FROM_ADDRESS,
            to: ADMIN_EMAIL,
            subject: subject,
            html: html,
        });
        console.log('[Alerts] Crawler report sent to', ADMIN_EMAIL);
    } catch (error) {
        console.error('[Alerts] Failed to send crawler report:', error);
    }
}
